language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

env:
  - SONAR_TOKEN=b72424f6b573f1e7b197654237901ac84727a6f6