server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    managementPort: 15672
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always